# Generated by Django 5.2.7 on 2025-11-19 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='password_must_change',
            field=models.BooleanField(default=False),
        ),
    ]
