# Generated by Django 5.2.7 on 2025-10-29 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Low', 'Baja'), ('Medium', 'Media'), ('High', 'Alta')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ej: UN, CAJA, KG', max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('ean_upc', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('model_name', models.CharField(blank=True, max_length=100, verbose_name='Modelo')),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=1.0, max_digits=12, verbose_name='Factor Conversión')),
                ('standard_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Costo Estándar')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio Venta Base')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Tasa IVA (%)')),
                ('stock_min', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Stock Mínimo')),
                ('stock_max', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Stock Máximo')),
                ('reorder_point', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True, verbose_name='Punto Reorden')),
                ('is_perishable', models.BooleanField(default=False, verbose_name='Perecible')),
                ('lot_controlled', models.BooleanField(default=False, verbose_name='Control por Lote')),
                ('serial_controlled', models.BooleanField(default=False, verbose_name='Control por Serie')),
                ('image_url', models.URLField(blank=True, max_length=255, verbose_name='URL Imagen')),
                ('datasheet_url', models.URLField(blank=True, max_length=255, verbose_name='URL Ficha Técnica')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible para venta')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalogo.category')),
                ('uom_purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_purchase', to='catalogo.unitofmeasure', verbose_name='UdM Compra')),
                ('uom_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_sale', to='catalogo.unitofmeasure', verbose_name='UdM Venta')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAlertRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('max_value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.alertrule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product')),
            ],
            options={
                'unique_together': {('product', 'alert_rule')},
            },
        ),
    ]
