# Generated by Django 5.2.7 on 2025-10-29 23:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18, verbose_name='Cantidad')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True, verbose_name='Costo Unitario')),
                ('lot_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serie')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Fecha Vencimiento')),
                ('doc_reference', models.CharField(blank=True, help_text='Ej: OC-123, FAC-456, GUIA-789', max_length=100, verbose_name='Doc. Referencia')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo (Ajuste/Dev.)')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InventoryMovementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Código Tipo Mov.')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre Tipo Mov.')),
                ('is_entry', models.BooleanField(help_text='Marca si suma al stock, desmarca si resta.', verbose_name='Es Entrada (+)')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=18, verbose_name='Cantidad Actual')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre Bodega')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Ubicación')),
            ],
        ),
    ]
