# Generated by Django 5.2.7 on 2025-10-29 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('inventario', '0001_initial'),
        ('proveedores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements_created', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.product', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.supplier', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.unitofmeasure', verbose_name='UdM'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventorymovementtype', verbose_name='Tipo Movimiento'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product'),
        ),
        migrations.AddField(
            model_name='inventorystock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.warehouse'),
        ),
        migrations.AddField(
            model_name='inventorymovement',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.warehouse', verbose_name='Bodega'),
        ),
    ]
