# Generated by Django 5.2.7 on 2025-10-29 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_nif', models.CharField(max_length=20, unique=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('nombre_fantasia', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('sitio_web', models.URLField(blank=True, max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('ciudad', models.CharField(blank=True, max_length=128)),
                ('pais', models.CharField(default='Chile', max_length=64)),
                ('condiciones_pago', models.CharField(max_length=100)),
                ('moneda', models.CharField(default='CLP', max_length=8)),
                ('contacto_principal_nombre', models.CharField(blank=True, max_length=120)),
                ('contacto_principal_email', models.EmailField(blank=True, max_length=254)),
                ('contacto_principal_telefono', models.CharField(blank=True, max_length=30)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=6, max_digits=18)),
                ('lead_time_days', models.IntegerField(default=7)),
                ('min_batch', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('discount_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_preferred', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.supplier')),
            ],
            options={
                'unique_together': {('product', 'supplier')},
            },
        ),
    ]
